/*
	ALEJANDRO MUNOZ VINDAS SCRIPT INICIAL DEL PROYECTO DESCUBRIENDO NUESTRS ECOEMPRESARIAS
	19/1/2026
*/

CREATE DATABASE Descubriendo_Nuestras_EcoEmpresarias;
GO

USE Descubriendo_Nuestras_EcoEmpresarias;
GO

CREATE USER 'usuario_proyecto'@'%' identified by 'Municipalidad Oreamuno';

grant all privileges on Descubriendo_Nuestas_EcoEmpresarias.* to 'usuario_proyecto'@'%';

USE Descubriendo_Nuestas_EcoEmpresarias;

/*CREACION DE LAS TABLAS*/

/*TABLA FIDE_ESTADOS*/

CREATE TABLE ECOEMPRESARIAS_ESTADOS_TB (
    Estado_id INT NOT NULL,
    Nombre VARCHAR(200) NOT NULL,
    CONSTRAINT ECO_ESTADOS_PK PRIMARY KEY (Estado_id)
);


CREATE TABLE ECOEMPRESARIAS_ROLES_TB (
    Rol_id INT NOT NULL,
    Nombre VARCHAR(200) NOT NULL,
    Estado_id INT NOT NULL,
    CONSTRAINT ECO_ROLES_PK PRIMARY KEY (Rol_id),
    CONSTRAINT ECO_ROLES_ESTADO_FK 
        FOREIGN KEY (Estado_id) REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);


CREATE TABLE ECOEMPRESARIAS_USUARIOS_TB (
    Usuario_id INT NOT NULL,
    Nombre VARCHAR(200) NOT NULL,
    Apellidos VARCHAR(200) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Contrasena VARCHAR(200) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    Ruta_Imagen_Perfil VARCHAR(300) NOT NULL,
    Edad INT NOT NULL,
    Estado_id INT NOT NULL,
    Rol_id INT NOT NULL,

    CONSTRAINT ECO_USUARIOS_PK PRIMARY KEY (Usuario_id),
    CONSTRAINT ECO_USUARIOS_ESTADO_FK FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),
    CONSTRAINT ECO_USUARIOS_ROL_FK FOREIGN KEY (Rol_id)
        REFERENCES ECOEMPRESARIAS_ROLES_TB(Rol_id),
    CONSTRAINT ECO_EMAIL_USUARIO_UNQ UNIQUE (Email),
    CONSTRAINT ECO_EDAD_USUARIO_CHK CHECK (Edad > 0)
);


CREATE TABLE ECOEMPRESARIAS_EMPRENDEDOR_TB (
    Emprendedor_id INT NOT NULL,
    Cedula VARCHAR(12) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    Estado_id INT NOT NULL,
    Usuario_id INT NOT NULL,

    CONSTRAINT ECO_EMPRENDEDOR_PK PRIMARY KEY (Emprendedor_id),
    CONSTRAINT ECO_EMPRENDEDOR_ESTADO_FK FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),
    CONSTRAINT ECO_EMPRENDEDOR_USUARIO_FK FOREIGN KEY (Usuario_id)
        REFERENCES ECOEMPRESARIAS_USUARIOS_TB(Usuario_id),
    CONSTRAINT ECO_EMAIL_EMPRENDEDOR_UNQ UNIQUE (Email),
    CONSTRAINT ECO_CEDULA_EMPRENDEDOR_UNQ UNIQUE (Cedula)
);


CREATE TABLE ECOEMPRESARIAS_EMPRENDIMIENTOS_TB (
    Emprendimiento_id INT NOT NULL,
    Cedula VARCHAR(12) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    Estado_id INT NOT NULL,
    Emprendedor_id INT NOT NULL,

    CONSTRAINT ECO_EMPRENDIMIENTO_PK PRIMARY KEY (Emprendimiento_id),
    CONSTRAINT ECO_EMPRENDIMIENTO_ESTADO_FK FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),
    CONSTRAINT ECO_EMPRENDIMIENTO_EMPRENDEDOR_FK FOREIGN KEY (Emprendedor_id)
        REFERENCES ECOEMPRESARIAS_EMPRENDEDOR_TB(Emprendedor_id),
    CONSTRAINT ECO_EMAIL_EMPRENDIMIENTO_UNQ UNIQUE (Email),
    CONSTRAINT ECO_CEDULA_EMPRENDIMIENTO_UNQ UNIQUE (Cedula)
);

CREATE TABLE ECOEMPRESARIAS_COMENTARIOS_TB (
    Comentario_id INT NOT NULL,
    Comentario VARCHAR(1000) NOT NULL,
    Fecha DATE NOT NULL,
    Calificacion FLOAT NOT NULL,
    Usuario_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_COMENTARIO_PK PRIMARY KEY (Comentario_id),
    CONSTRAINT ECO_COMENTARIO_ESTADO_FK FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),
    CONSTRAINT ECO_COMENTARIO_USUARIO_FK FOREIGN KEY (Usuario_id)
        REFERENCES ECOEMPRESARIAS_USUARIOS_TB(Usuario_id)
);






CREATE TABLE ECOEMPRESARIAS_EVENTOS_TB (
    Evento_id INT NOT NULL,
    NombreEvento VARCHAR(200) NOT NULL,
    Descripcion VARCHAR(500) NOT NULL,
    Fecha_inicio DATE NOT NULL,
	Fecha_final DATE NOT NULL,
    Horario TIME NOT NULL,
	Cupos INT NOT NULL,
	Cupos_actuales INT NOT NULL,
    Lugar_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_EVENTOS_PK PRIMARY KEY (Evento_id),
    CONSTRAINT ECO_EVENTOS_ESTADO_FK FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),
    CONSTRAINT ECO_EVENTOS_CUPOS_CHK CHECK (Cupos >= 0)
);


CREATE TABLE ECOEMPRESARIAS_RESERVA_EVENTOS_TB (
    Emprendimiento_id INT NOT NULL,
    Evento_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_RESERVA_EVENTOS_PK 
        PRIMARY KEY (Emprendimiento_id, Evento_id),

    CONSTRAINT ECO_RESERVA_EVENTOS_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),

    CONSTRAINT ECO_RESERVA_EVENTOS_EMPRENDIMIENTO_FK
        FOREIGN KEY (Emprendimiento_id)
        REFERENCES ECOEMPRESARIAS_EMPRENDIMIENTOS_TB(Emprendimiento_id),

    CONSTRAINT ECO_RESERVA_EVENTOS_EVENTO_FK
        FOREIGN KEY (Evento_id)
        REFERENCES ECOEMPRESARIAS_EVENTOS_TB(Evento_id)
);




CREATE TABLE ECOEMPRESARIAS_CATEGORIA_TB (
    Categoria_id INT NOT NULL,
    Nombre VARCHAR(200) NOT NULL,
    Ruta_imagen VARCHAR(300) NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_CATEGORIA_PK PRIMARY KEY (Categoria_id),
    CONSTRAINT ECO_CATEGORIA_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);

CREATE TABLE ECOEMPRESARIAS_PRODUCTO_TB (
    Producto_id INT NOT NULL,
    NombreProducto VARCHAR(200) NOT NULL,
    Descripcion VARCHAR(500) NOT NULL,
    Ruta_Imagen VARCHAR(300) NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    Categoria_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_PRODUCTO_PK PRIMARY KEY (Producto_id),
    CONSTRAINT ECO_PRODUCTO_PRECIO_CHK CHECK (Precio >= 0),
    CONSTRAINT ECO_PRODUCTO_CATEGORIA_FK 
        FOREIGN KEY (Categoria_id)
        REFERENCES ECOEMPRESARIAS_CATEGORIA_TB(Categoria_id),
    CONSTRAINT ECO_PRODUCTO_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);



CREATE TABLE ECOEMPRESARIAS_INVENTARIO_TB (
    Producto_id INT NOT NULL,
    Cantidad_actual DECIMAL(10,2) NOT NULL,
    Cantidad_minima DECIMAL(10,2) NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_INVENTARIO_PK PRIMARY KEY (Producto_id),
    CONSTRAINT ECO_INVENTARIO_CANT_ACT_CHK CHECK (Cantidad_actual >= 0),
    CONSTRAINT ECO_INVENTARIO_CANT_MIN_CHK CHECK (Cantidad_minima >= 0),
    CONSTRAINT ECO_INVENTARIO_PRODUCTO_FK 
        FOREIGN KEY (Producto_id)
        REFERENCES ECOEMPRESARIAS_PRODUCTO_TB(Producto_id),
    CONSTRAINT ECO_INVENTARIO_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);



CREATE TABLE ECOEMPRESARIAS_CARRITO_TB (
    Carrito_id INT NOT NULL,
    Cantidad DECIMAL(10,2) NOT NULL,
    Usuario_id INT NOT NULL,
    Producto_id UNIQUEIDENTIFIER NOT NULL,

    CONSTRAINT ECO_CARRITO_PK PRIMARY KEY (Carrito_id),
    CONSTRAINT ECO_CARRITO_CANTIDAD_CHK CHECK (Cantidad > 0),
    CONSTRAINT ECO_CARRITO_USUARIO_FK 
        FOREIGN KEY (Usuario_id)
        REFERENCES ECOEMPRESARIAS_USUARIOS_TB(Usuario_id),
    CONSTRAINT ECO_CARRITO_PRODUCTO_FK 
        FOREIGN KEY (Producto_id)
        REFERENCES ECOEMPRESARIAS_PRODUCTO_TB(Producto_id)
);



CREATE TABLE ECOEMPRESARIAS_FACTURAS_TB (
    Factura_id INT NOT NULL,
    Fecha DATE NOT NULL,
    Total DECIMAL(10,2) NOT NULL,
    IVA DECIMAL(10,2) NOT NULL,
    Descuento DECIMAL(10,2) NOT NULL,
    Estado_id INT NOT NULL,
    Usuario_id INT NOT NULL,
    Emprendimiento_id INT NOT NULL,

    CONSTRAINT ECO_FACTURAS_PK PRIMARY KEY (Factura_id),
    CONSTRAINT ECO_FACTURAS_TOTAL_CHK CHECK (Total >= 0),
    CONSTRAINT ECO_FACTURAS_IVA_CHK CHECK (IVA >= 0),
    CONSTRAINT ECO_FACTURAS_DESC_CHK CHECK (Descuento >= 0),

    CONSTRAINT ECO_FACTURAS_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),
    CONSTRAINT ECO_FACTURAS_USUARIO_FK 
        FOREIGN KEY (Usuario_id)
        REFERENCES ECOEMPRESARIAS_USUARIOS_TB(Usuario_id),
    CONSTRAINT ECO_FACTURAS_EMPRENDIMIENTO_FK 
        FOREIGN KEY (Emprendimiento_id)
        REFERENCES ECOEMPRESARIAS_EMPRENDIMIENTOS_TB(Emprendimiento_id)
);



CREATE TABLE ECOEMPRESARIAS_DETALLE_FACTURAS_TB (
    Factura_id INT NOT NULL,
    Producto_id UNIQUEIDENTIFIER NOT NULL,
    Cantidad DECIMAL(10,2) NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_DETALLE_FACTURAS_PK PRIMARY KEY (Factura_id, Producto_id),

    CONSTRAINT ECO_DETALLE_FACT_CANT_CHK CHECK (Cantidad > 0),
    CONSTRAINT ECO_DETALLE_FACT_PRECIO_CHK CHECK (Precio >= 0),

    CONSTRAINT ECO_DETALLE_FACT_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),

    CONSTRAINT ECO_DETALLE_FACT_FACTURA_FK
        FOREIGN KEY (Factura_id)
        REFERENCES ECOEMPRESARIAS_FACTURAS_TB(Factura_id),

    CONSTRAINT ECO_DETALLE_FACT_PRODUCTO_FK
        FOREIGN KEY (Producto_id)
        REFERENCES ECOEMPRESARIAS_PRODUCTO_TB(Producto_id)
);



--ALEJANDRO MUNOZ VINDAS 17/2/2026
---ESTADOS Y SUS ID 
--ACTIVO -> ID: 1
--INACTIVO -> ID: 2
--PRODUCTO CREADO PENDIENTE -> ID: 3
--PRODUCTO EDITADO PENDIENTE ->ID: 4


SELECT * FROM ECOEMPRESARIAS_ESTADOS_TB

---Estados 
INSERT INTO ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre) VALUES (0, 'INACTIVO');
INSERT INTO ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre) VALUES (1, 'ACTIVO');
INSERT INTO ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre) VALUES (2, 'PRODUCTO CREADO PENDIENTE');
INSERT INTO ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre) VALUES (3, 'PRODUCTO EDITADO PENDIENTE');
INSERT INTO ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre) VALUES (4, 'RECHAZADO');

--Roles
INSERT INTO ECOEMPRESARIAS_ROLES_TB(Rol_id,Nombre,Estado_id) values(1,'ADMIN',1);
INSERT INTO ECOEMPRESARIAS_ROLES_TB(Rol_id,Nombre,Estado_id) values(1,'EMPRENDEDOR',1);
INSERT INTO ECOEMPRESARIAS_ROLES_TB(Rol_id,Nombre,Estado_id) values(1,'USUARIO',1);


--MODIFICACION DE LAS TABLA DE EVENTOS

CREATE TABLE ECOEMPRESARIAS_EVENTOS_TB (
    Evento_id INT IDENTITY NOT NULL,
    NombreEvento VARCHAR(200) NOT NULL,
    Descripcion VARCHAR(500) NOT NULL,
    Fecha_inicio DATE NOT NULL,
	Fecha_final DATE NOT NULL,
    Horario TIME NOT NULL,
	Cupos INT NOT NULL,
	Cupos_actuales INT NOT NULL,
    Lugar_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_EVENTOS_PK PRIMARY KEY (Evento_id),

	CONSTRAINT ECO_EVENTOS_LUGAR_FK FOREIGN KEY (Lugar_id)
        REFERENCES ECOEMPRESARIAS_LUGARES_TB(Lugar_id),

    CONSTRAINT ECO_EVENTOS_ESTADO_FK FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),

    CONSTRAINT ECO_EVENTOS_CUPOS_CHK CHECK (Cupos >= 0),

	CONSTRAINT ECO_EVENTOS_CUPOS_ACTUALES_CHK CHECK (Cupos_actuales >= 0)
);


CREATE TABLE ECOEMPRESARIAS_RESERVA_EVENTOS_TB (
    Emprendimiento_id INT NOT NULL,
    Evento_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_RESERVA_EVENTOS_PK 
        PRIMARY KEY (Emprendimiento_id, Evento_id),

    CONSTRAINT ECO_RESERVA_EVENTOS_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),

    CONSTRAINT ECO_RESERVA_EVENTOS_EMPRENDIMIENTO_FK
        FOREIGN KEY (Emprendimiento_id)
        REFERENCES ECOEMPRESARIAS_EMPRENDIMIENTOS_TB(Emprendimiento_id),

    CONSTRAINT ECO_RESERVA_EVENTOS_EVENTO_FK
        FOREIGN KEY (Evento_id)
        REFERENCES ECOEMPRESARIAS_EVENTOS_TB(Evento_id)
);



--NUEVAS TABLAS PARA LA SECCION DE EVENTOS

CREATE TABLE ECOEMPRESARIAS_LUGARES_TB  (
    
    Lugar_id INT IDENTITY NOT NULL,
    Nombre NVARCHAR(200) NOT NULL,
    Provincia NVARCHAR(200) NOT NULL,
    Canton NVARCHAR(200) NOT NULL,
    Distrito NVARCHAR(200) NOT NULL,
    Detalles NVARCHAR(MAX),
    Estado_id INT NOT NULL,

    CONSTRAINT PK_ECO_LUGARES_TB 
        PRIMARY KEY (Lugar_id),

	 CONSTRAINT ECO_LUGAR_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),

);


CREATE TABLE ECOEMPRESARIAS_PISOS_TB(

    Piso_id INT IDENTITY(1,1) NOT NULL,
    Nombre_piso NVARCHAR(150) NOT NULL,
    Numero_piso INT NOT NULL,
    Lugar_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT PK_ECOEMPRESARIAS_PISOS_TB 
        PRIMARY KEY (Piso_id),

    CONSTRAINT FK_ECOEMPRESARIAS_PISOS_LUGAR
        FOREIGN KEY (Lugar_id)
        REFERENCES ECOEMPRESARIAS_LUGARES_TB(Lugar_id),

	 CONSTRAINT ECO_PISO_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id),

);

CREATE TABLE ECOEMPRESARIAS_MAPAS_TB (

    Mapa_id INT IDENTITY(1,1) NOT NULL,
    Nombre NVARCHAR(150) NOT NULL,
    Alto INT NOT NULL,
    Ancho INT NOT NULL,
    Escala DECIMAL(10,2) NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT PK_ECOEMPRESARIAS_MAPAS_TB
        PRIMARY KEY (Mapa_id),

    CONSTRAINT ECO_MAPAS_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)

);


CREATE TABLE ECOEMPRESARIAS_ZONAS_TB (

    Zona_id INT IDENTITY(1,1) NOT NULL,
    Nombre NVARCHAR(150) NOT NULL,
    Descripcion NVARCHAR(MAX) NULL,
    Piso_id INT NOT NULL,
    Mapa_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT PK_ECOEMPRESARIAS_ZONAS_TB
        PRIMARY KEY (Zona_id),

    CONSTRAINT FK_ECOEMPRESARIAS_ZONAS_PISO
        FOREIGN KEY (Piso_id)
        REFERENCES ECOEMPRESARIAS_PISOS_TB(Piso_id),

    CONSTRAINT FK_ECOEMPRESARIAS_ZONAS_MAPA
        FOREIGN KEY (Mapa_id)
        REFERENCES ECOEMPRESARIAS_MAPAS_TB(Mapa_id),

	CONSTRAINT ECO_ZONA_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)

);

CREATE TABLE ECOEMPRESARIAS_STANDS_MAPAS_TB (

    Stand_id INT IDENTITY(1,1) NOT NULL,
    Codigo NVARCHAR(50) NOT NULL,
    X INT NOT NULL,
    Y INT NOT NULL,
    Ancho INT NOT NULL,
    Alto INT NOT NULL,
    Rotacion INT NULL,
    Mapa_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT PK_ECOEMPRESARIAS_STANDS_MAPAS_TB
        PRIMARY KEY (Stand_id),

    CONSTRAINT FK_ECOEMPRESARIAS_STANDS_MAPA
        FOREIGN KEY (Mapa_id)
        REFERENCES ECOEMPRESARIAS_MAPAS_TB(Mapa_id),

   CONSTRAINT ECO_STAND_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)

);

--APARTIR DE AQUI SON LAS TABLAS QUE MANEJAN LA LOGICA DE DISPONIBILIDAD DE PISOS, ZONAS Y STANDS POR EVENTO

--ESTA TABLA ES PARA INDICAR QUE PISOS ESTAN HABILITADOS PARA CADA EVENTO
CREATE TABLE ECOEMPRESARIAS_EVENTO_PISOS_TB (
    Evento_id INT NOT NULL,
    Piso_id INT NOT NULL,
    Estado_id INT NOT NULL,

    CONSTRAINT ECO_EVENTO_PISOS_FK PRIMARY KEY (Evento_id, Piso_id),
    
    CONSTRAINT ECO_EVENTO_PISOS_EVENTO_FK
        FOREIGN KEY (Evento_id)
        REFERENCES ECOEMPRESARIAS_EVENTOS_TB(Evento_id),

    CONSTRAINT ECO_EVENTO_PISOS_PISO_FK
        FOREIGN KEY (Piso_id)
        REFERENCES ECOEMPRESARIAS_PISOS_TB(Piso_id),

	CONSTRAINT ECO_EVENTO_PISO_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);


CREATE TABLE ECOEMPRESARIAS_EVENTOS_ZONAS_TB (
    Evento_id INT NOT NULL,
    Zona_id   INT NOT NULL,
    Estado_id INT NOT NULL,

    
    CONSTRAINT ECO_EVENTO_ZONAS_PK PRIMARY KEY (Evento_id, Zona_id),
    
    CONSTRAINT ECO_EVENTO_ZONAS_EVENTO_FK
        FOREIGN KEY (Evento_id)
        REFERENCES ECOEMPRESARIAS_EVENTOS_TB(Evento_id),

    CONSTRAINT ECO_EVENTO_ZONAS_ZONA_FK
        FOREIGN KEY (Zona_id)
        REFERENCES ECOEMPRESARIAS_ZONAS_TB(Zona_id),

    CONSTRAINT ECO_EVENTO_ZONA_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);

CREATE TABLE ECOEMPRESARIAS_EVENTOS_ZONAS_STANDS_TB (

    Stand_id         INT NOT NULL,
    Zona_id          INT NOT NULL,
    Evento_id        INT NOT NULL,
    Emprendimientos_id INT NULL, 
    Estado_id        INT NOT NULL,

    CONSTRAINT ECO_EVENTO_ZONAS_STANDS_PK PRIMARY KEY (Stand_id, Zona_id, Evento_id),
    
    CONSTRAINT ECO_EVENTO_ZONAS_STANDS_STAND_FK
        FOREIGN KEY (Stand_id)
        REFERENCES ECOEMPRESARIAS_STANDS_MAPAS_TB(Stand_id),

    CONSTRAINT ECO_EVENTO_ZONAS_STANDS_ZONA_FK
        FOREIGN KEY (Zona_id)
        REFERENCES ECOEMPRESARIAS_ZONAS_TB(Zona_id),

    CONSTRAINT ECO_EVENTO_ZONAS_STANDS_EVENTO_FK
        FOREIGN KEY (Evento_id)
        REFERENCES ECOEMPRESARIAS_EVENTOS_TB(Evento_id),

    CONSTRAINT ECO_EVENTO_ZONAS_STANDS_EMPRENDIMIENTO_FK
        FOREIGN KEY (Emprendimientos_id)
        REFERENCES ECOEMPRESARIAS_EMPRENDIMIENTOS_TB(Emprendimiento_id),

    CONSTRAINT ECO_EVENTO_ZONAS_STANDS_ESTADO_FK 
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB(Estado_id)
);


---inserts en la tabla de estados
Insert into ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre)
VALUES 
(8, 'Reserva evento Pendiente'),
(9, 'Reserva evento Aceptada'),
(10, 'Reserva evento Rechazada')

---inserts en la tabla de estados
Insert into ECOEMPRESARIAS_ESTADOS_TB(Estado_id, Nombre)
VALUES 
(11, 'DISPONIBLE'),
(12, 'OCUPADO'),
(13, 'BLOQUEADO')