/*
	ALEJANDRO MUNOZ VINDAS SCRIPT INICIAL DEL PROYECTO DESCUBRIENDO NUESTRS ECOEMPRESARIAS
	19/1/2026
*/

CREATE SCHEMA Descubriendo_Nuestas_EcoEmpresarias;

CREATE USER 'usuario_proyecto'@'%' identified by 'Municipalidad Oreamuno';

grant all privileges on Descubriendo_Nuestas_EcoEmpresarias.* to 'usuario_proyecto'@'%';

USE Descubriendo_Nuestas_EcoEmpresarias;

/*CREACION DE LAS TABLAS*/

/*TABLA FIDE_ESTADOS*/

CREATE TABLE FIDE_ESTADOS_TB (
	Estado_id INT,
	Nombre VARCHAR(200),
    CONSTRAINT FIDE_ESTADOS_PK PRIMARY KEY(Estado_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_ROLES_TB (
	Rol_id INT,
	Nombre VARCHAR(200),
    Estado_id INT,
    CONSTRAINT FIDE_ROLES_PK PRIMARY KEY(Rol_id),
    CONSTRAINT FIDE_ROLES_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id)
)
	ENGINE = InnoDB
	DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_USUARIOS_TB (
    Usuario_id INT,
    Nombre VARCHAR(200),
    Apellidos VARCHAR(200),
    Telefono VARCHAR(15),
    Contrasena VARCHAR(200),
    Email VARCHAR(200),
    Ruta_Imagen_Perfil VARCHAR(300),
    Edad INT,
    Estado_id INT,
    Rol_id INT,
    CONSTRAINT FIDE_USUARIOS_PK PRIMARY KEY(Usuario_id),
    CONSTRAINT FIDE_USUARIOS_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id),
    CONSTRAINT FIDE_USUARIOS_ROL_FK FOREIGN KEY(Rol_id) REFERENCES FIDE_ROLES_TB(Rol_id),
	CONSTRAINT FIDE_EMAIL_USUARIO_UNIQUE UNIQUE(Email),
    CONSTRAINT FIDE_EDAD_USUARIO_CHECK CHECK(Edad>0)
)
	ENGINE = InnoDB
	DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_EMPRENDEDOR_TB (
	Emprendedor_id INT,
    Cedula VARCHAR(12),
    Telefono varchar(15),
    Email VARCHAR(200),
    Estado_id INT,
    Usuario_id INT,
	CONSTRAINT FIDE_EMPRENDEDOR_PK PRIMARY KEY(Emprendedor_id),
	CONSTRAINT FIDE_EMPRENDEDOR_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id),
    CONSTRAINT FIDE_EMPRENDEDOR_USUARIO_ID_FK FOREIGN KEY(Usuario_id) REFERENCES FIDE_USUARIOS_TB(Usuario_id),
	CONSTRAINT FIDE_EMAIL_EMPRENDEDOR_UNIQUE UNIQUE(Email),
    CONSTRAINT FIDE_CEDULA_EMPRENDEDOR_UNIQUE UNIQUE(Cedula)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE FIDE_EMPRENDIMIENTOS_TB(
	Emprendimiento_id INT,
	Cedula VARCHAR(12),
    Telefono varchar(15),
    Email VARCHAR(200),
    Estado_id INT,
	Emprendedor_id INT,
    CONSTRAINT FIDE_EMPRENDIMIENTO_PK PRIMARY KEY(Emprendimiento_id),
    CONSTRAINT FIDE_EMPRENDIMIENTO_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id),
    CONSTRAINT FIDE_EMPRENDIMIENTO_EMPRENDEDOR_ID_FK FOREIGN KEY(Emprendedor_id) REFERENCES FIDE_EMPRENDEDOR_TB(Emprendedor_id),
	CONSTRAINT FIDE_EMAIL_EMPRENDIMIENTO_UNIQUE UNIQUE(Email),
    CONSTRAINT FIDE_CEDULA_EMPRENDIMEINTO_UNIQUE UNIQUE(Cedula)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE FIDE_COMENTARIOS_TB(
	Comentario_id INT,
    Comentario Varchar(1000),
    Fecha DATE,
    Calificacion DOUBLE,
	Usuario_id INT,
    Estado_id INT,
	CONSTRAINT FIDE_COMENTARIO_PK PRIMARY KEY(Comentario_id),
	CONSTRAINT FIDE_COMENTARIO_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id),
	CONSTRAINT FIDE_COMENTARIO_USUARIO_ID_FK FOREIGN KEY(Usuario_id) REFERENCES FIDE_USUARIOS_TB(Usuario_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE FIDE_EVENTOS_TB (
    Evento_id INT,
    NombreEvento VARCHAR(200),
    Descripcion VARCHAR(500),
    Fecha DATE,
    Horario TIME,
    Lugar VARCHAR(300),
    Cupos INT,
    Estado_id INT,
    CONSTRAINT FIDE_EVENTOS_PK PRIMARY KEY(Evento_id),
    CONSTRAINT FIDE_EVENTOS_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id),
    CONSTRAINT FIDE_EVENTOS_CHECK_CUPOS CHECK(Cupos>=0)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE FIDE_RESERVA_EVENTOS_TB(
	Emprendimiento_id INT,
    Evento_id INT,
    Estado_id INT,
    CONSTRAINT FIDE_RESERVA_EVENTOS_PK PRIMARY KEY(Emprendimiento_id,Evento_id),
    CONSTRAINT FIDE_RESERVA_EVENTOS_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE FIDE_CATEGORIA_TB(
	Categoria_id INT,
    Nombre VARCHAR(200),
    Ruta_imagen VARCHAR(300),
    Estado_id INT,
    CONSTRAINT FIDE_CATEGORIA_PK PRIMARY KEY(Categoria_id),
    CONSTRAINT FIDE_CATEGORIA_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE FIDE_PRODUCTO_TB (
    Producto_id INT,
    NombreProducto VARCHAR(200),
    Descripcion VARCHAR(500),
    Ruta_Imagen VARCHAR(300),
    Precio DECIMAL(10,2),
    Categoria_id INT,
    Estado_id INT,
    CONSTRAINT FIDE_PRODUCTO_PK PRIMARY KEY(Producto_id),
    CONSTRAINT FIDE_PRODUCTO_PRECIO_CHK CHECK (Precio >= 0),
    CONSTRAINT FIDE_PRODUCTO_CATEGORIA_FK FOREIGN KEY(Categoria_id) REFERENCES FIDE_CATEGORIA_TB(Categoria_id),
    CONSTRAINT FIDE_PRODUCTO_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_INVENTARIO_TB(
	Producto_id INT,
    Cantidad_actual DECIMAL(10,2),
    Cantidad_minima DECIMAL(10,2),
    Estado_id INT,
    CONSTRAINT FIDE_Inventario_PK PRIMARY KEY(Producto_id),
    CONSTRAINT FIDE_INVENTARIO_CANTIDAD_ACTUAL_CHK CHECK (Cantidad_actual >= 0),
    CONSTRAINT FIDE_INVENTARIO_CANTIDAD_MINIMA_CHK CHECK (Cantidad_minima >= 0),
	CONSTRAINT FIDE_INVENTARIO_PRODUCTO_FK FOREIGN KEY(Producto_id) REFERENCES FIDE_PRODUCTO_TB(Producto_id),
    CONSTRAINT FIDE_INVENTARIO_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_CARRITO_TB (
	Carrito_id INT,
    Cantidad DECIMAL(10,2),
    Usuario_id INT,
    Producto_id INT, 
	CONSTRAINT FIDE_CARRITO_PK PRIMARY KEY(Carrito_id),
    CONSTRAINT FIDE_CANTIDAD_CHK CHECK (Cantidad > 0),
    CONSTRAINT FIDE_CARRITO_PRODUCTO_FK FOREIGN KEY(Producto_id) REFERENCES FIDE_PRODUCTO_TB(Producto_id),
    CONSTRAINT FIDE_CARRITO_USUARIO_FK FOREIGN KEY(Usuario_id) REFERENCES FIDE_USUARIOS_TB(Usuario_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_FACTURAS_TB (
    Factura_id INT,
    Fecha DATE,
    Total DECIMAL(10,2),
    IVA DECIMAL(10,2),
    Descuento DECIMAL(10,2),
    Estado_id INT,
    Usuario_id INT,
    Emprendimiento_id INT,

    CONSTRAINT FIDE_FACTURAS_PK PRIMARY KEY(Factura_id),

    CONSTRAINT FIDE_FACTURAS_TOTAL_CHK CHECK (Total >= 0),
    CONSTRAINT FIDE_FACTURAS_IVA_CHK CHECK (IVA >= 0),
    CONSTRAINT FIDE_FACTURAS_DESCUENTO_CHK CHECK (Descuento >= 0),

    CONSTRAINT FIDE_FACTURAS_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id),
    CONSTRAINT FIDE_FACTURAS_USUARIO_FK FOREIGN KEY(Usuario_id) REFERENCES FIDE_USUARIOS_TB(Usuario_id),
    CONSTRAINT FIDE_FACTURAS_EMPRENDIMIENTO_FK FOREIGN KEY(Emprendimiento_id) REFERENCES FIDE_EMPRENDIMIENTOS_TB(Emprendimiento_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE FIDE_DETALLE_FACTURAS_TB(
	Factura_id INT,
    Producto_id INT,
    Cantidad DECIMAL(10,2),
    Precio DECIMAL(10,2),
    Estado_id INT,
	CONSTRAINT FIDE_DETALLE_FACTURAS_PK PRIMARY KEY(Factura_id, Producto_id),
	CONSTRAINT FIDE_DETALLES_FACTURAS_CANTIDAD_CHK CHECK (Cantidad > 0),
    CONSTRAINT FIDE_DETALLES_FACTURAS_PRECIO_CHK CHECK (Precio >= 0),
	CONSTRAINT FIDE_DETALLES_FACTURAS_ESTADO_FK FOREIGN KEY(Estado_id) REFERENCES FIDE_ESTADOS_TB(Estado_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;







