CREATE TABLE [dbo].[ECOEMPRESARIAS_RESERVA_EVENTOS_TB] (
    [Emprendimiento_id] INT NOT NULL,
    [Evento_id]         INT NOT NULL,
    [Estado_id]         INT NOT NULL,
    CONSTRAINT [ECO_RESERVA_EVENTOS_PK] PRIMARY KEY CLUSTERED ([Emprendimiento_id] ASC, [Evento_id] ASC),
    CONSTRAINT [ECO_RESERVA_EVENTOS_EMPRENDIMIENTO_FK] FOREIGN KEY ([Emprendimiento_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EMPRENDIMIENTOS_TB] ([Emprendimiento_id]),
    CONSTRAINT [ECO_RESERVA_EVENTOS_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_RESERVA_EVENTOS_EVENTO_FK] FOREIGN KEY ([Evento_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EVENTOS_TB] ([Evento_id])
);

