CREATE TABLE [dbo].[ECOEMPRESARIAS_DETALLE_FACTURAS_TB] (

    Factura_id INT NOT NULL,
    Producto_id UNIQUEIDENTIFIER NOT NULL,

    Cantidad DECIMAL(10,2) NOT NULL,
    PrecioUnitario DECIMAL(10,2) NOT NULL,
    Subtotal DECIMAL(10,2) NOT NULL,

    Estado_id INT NOT NULL,

    CONSTRAINT ECO_DETALLE_FACTURAS_PK
        PRIMARY KEY (Factura_id, Producto_id),

    CONSTRAINT ECO_DETALLE_FACT_CANT_CHK
        CHECK (Cantidad > 0),

    CONSTRAINT ECO_DETALLE_FACT_PRECIO_CHK
        CHECK (PrecioUnitario >= 0),

    CONSTRAINT ECO_DETALLE_FACT_SUBTOTAL_CHK
        CHECK (Subtotal >= 0),

    CONSTRAINT ECO_DETALLE_FACT_FACTURA_FK
        FOREIGN KEY (Factura_id)
        REFERENCES ECOEMPRESARIAS_FACTURAS_TB (Factura_id),

    CONSTRAINT ECO_DETALLE_FACT_PRODUCTO_FK
        FOREIGN KEY (Producto_id)
        REFERENCES ECOEMPRESARIAS_PRODUCTO_TB (Producto_id),

    CONSTRAINT ECO_DETALLE_FACT_ESTADO_FK
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB (Estado_id)

);