CREATE TABLE [dbo].[ECOEMPRESARIAS_EVENTOS_ZONAS_TB] (
    [Evento_id] INT NOT NULL,
    [Zona_id]   INT NOT NULL,
    [Estado_id] INT NOT NULL,
    CONSTRAINT [ECO_EVENTO_ZONAS_PK] PRIMARY KEY CLUSTERED ([Evento_id] ASC, [Zona_id] ASC),
    CONSTRAINT [ECO_EVENTO_ZONA_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_EVENTO_ZONAS_EVENTO_FK] FOREIGN KEY ([Evento_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EVENTOS_TB] ([Evento_id]),
    CONSTRAINT [ECO_EVENTO_ZONAS_ZONA_FK] FOREIGN KEY ([Zona_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ZONAS_TB] ([Zona_id])
);

