CREATE TABLE [dbo].[ECOEMPRESARIAS_CARRITO_TB] (
    [Carrito_id]        UNIQUEIDENTIFIER NOT NULL,
    [Usuario_id]        INT              NOT NULL,
    [Emprendimiento_id] INT              NOT NULL,
    [FechaCreacion]     DATETIME         CONSTRAINT [ECO_CARRITO_TB_FECHACREACION_DF] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [ECO_CARRITO_TB_PK] PRIMARY KEY CLUSTERED ([Carrito_id] ASC),
    CONSTRAINT [ECO_CARRITO_TB_EMPRENDIMIENTO_FK] FOREIGN KEY ([Emprendimiento_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EMPRENDIMIENTOS_TB] ([Emprendimiento_id]),
    CONSTRAINT [ECO_CARRITO_TB_USUARIO_FK] FOREIGN KEY ([Usuario_id]) REFERENCES [dbo].[ECOEMPRESARIAS_USUARIOS_TB] ([Usuario_id]),
    CONSTRAINT [ECO_CARRITO_TB_USUARIO_EMPRENDIMIENTO_UQ] UNIQUE NONCLUSTERED ([Usuario_id] ASC, [Emprendimiento_id] ASC)
);

