CREATE TABLE [dbo].[ECOEMPRESARIAS_EVENTOS_ZONAS_STANDS_TB] (
    [Stand_id]           INT NOT NULL,
    [Zona_id]            INT NOT NULL,
    [Evento_id]          INT NOT NULL,
    [Emprendimientos_id] INT NULL,
    [Estado_id]          INT NOT NULL,
    CONSTRAINT [ECO_EVENTO_ZONAS_STANDS_PK] PRIMARY KEY CLUSTERED ([Stand_id] ASC, [Zona_id] ASC, [Evento_id] ASC),
    CONSTRAINT [ECO_EVENTO_ZONAS_STANDS_EMPRENDIMIENTO_FK] FOREIGN KEY ([Emprendimientos_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EMPRENDIMIENTOS_TB] ([Emprendimiento_id]),
    CONSTRAINT [ECO_EVENTO_ZONAS_STANDS_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_EVENTO_ZONAS_STANDS_EVENTO_FK] FOREIGN KEY ([Evento_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EVENTOS_TB] ([Evento_id]),
    CONSTRAINT [ECO_EVENTO_ZONAS_STANDS_STAND_FK] FOREIGN KEY ([Stand_id]) REFERENCES [dbo].[ECOEMPRESARIAS_STANDS_MAPAS_TB] ([Stand_id]),
    CONSTRAINT [ECO_EVENTO_ZONAS_STANDS_ZONA_FK] FOREIGN KEY ([Zona_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ZONAS_TB] ([Zona_id])
);

