CREATE TABLE [dbo].[ECOEMPRESARIAS_EMPRENDIMIENTOS_TB] (
    [Emprendimiento_id] INT           NOT NULL,
    [Cedula]            VARCHAR (12)  NOT NULL,
    [Telefono]          VARCHAR (15)  NOT NULL,
    [Email]             VARCHAR (200) NOT NULL,
    [Estado_id]         INT           NOT NULL,
    [Emprendedor_id]    INT           NOT NULL,
    CONSTRAINT [ECO_EMPRENDIMIENTO_PK] PRIMARY KEY CLUSTERED ([Emprendimiento_id] ASC),
    CONSTRAINT [ECO_EMPRENDIMIENTO_EMPRENDEDOR_FK] FOREIGN KEY ([Emprendedor_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EMPRENDEDOR_TB] ([Emprendedor_id]),
    CONSTRAINT [ECO_EMPRENDIMIENTO_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_CEDULA_EMPRENDIMIENTO_UNQ] UNIQUE NONCLUSTERED ([Cedula] ASC),
    CONSTRAINT [ECO_EMAIL_EMPRENDIMIENTO_UNQ] UNIQUE NONCLUSTERED ([Email] ASC)
);

