CREATE TABLE [dbo].[ECOEMPRESARIAS_ZONAS_TB] (
    [Zona_id]     INT            IDENTITY (1, 1) NOT NULL,
    [Nombre]      NVARCHAR (150) NOT NULL,
    [Descripcion] NVARCHAR (MAX) NULL,
    [Piso_id]     INT            NOT NULL,
    [Mapa_id]     INT            NULL,
    [Estado_id]   INT            NOT NULL,
    CONSTRAINT [PK_ECOEMPRESARIAS_ZONAS_TB] PRIMARY KEY CLUSTERED ([Zona_id] ASC),
    CONSTRAINT [ECO_ZONA_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [FK_ECOEMPRESARIAS_ZONAS_MAPA] FOREIGN KEY ([Mapa_id]) REFERENCES [dbo].[ECOEMPRESARIAS_MAPAS_TB] ([Mapa_id]),
    CONSTRAINT [FK_ECOEMPRESARIAS_ZONAS_PISO] FOREIGN KEY ([Piso_id]) REFERENCES [dbo].[ECOEMPRESARIAS_PISOS_TB] ([Piso_id])
);

