CREATE TABLE [dbo].[ECOEMPRESARIAS_FACTURAS_TB] (

    Factura_id INT IDENTITY(1,1) NOT NULL,
    Fecha DATE NOT NULL DEFAULT GETDATE(),

    Subtotal DECIMAL(10,2) NOT NULL,
    IVA DECIMAL(10,2) NOT NULL,
    Total DECIMAL(10,2) NOT NULL,

    Estado_id INT NOT NULL,
    Usuario_id INT NOT NULL,
    Emprendimiento_id INT NOT NULL,

    CONSTRAINT ECO_FACTURAS_PK
        PRIMARY KEY (Factura_id),

    CONSTRAINT ECO_FACTURAS_SUBTOTAL_CHK
        CHECK (Subtotal >= 0),

    CONSTRAINT ECO_FACTURAS_IVA_CHK
        CHECK (IVA >= 0),

    CONSTRAINT ECO_FACTURAS_TOTAL_CHK
        CHECK (Total >= 0),

    CONSTRAINT ECO_FACTURAS_ESTADO_FK
        FOREIGN KEY (Estado_id)
        REFERENCES ECOEMPRESARIAS_ESTADOS_TB (Estado_id),

    CONSTRAINT ECO_FACTURAS_USUARIO_FK
        FOREIGN KEY (Usuario_id)
        REFERENCES ECOEMPRESARIAS_USUARIOS_TB (Usuario_id),

    CONSTRAINT ECO_FACTURAS_EMPRENDIMIENTO_FK
        FOREIGN KEY (Emprendimiento_id)
        REFERENCES ECOEMPRESARIAS_EMPRENDIMIENTOS_TB (Emprendimiento_id)

);