CREATE TABLE [dbo].[ECOEMPRESARIAS_EVENTO_PISOS_TB] (
    [Evento_id] INT NOT NULL,
    [Piso_id]   INT NOT NULL,
    [Estado_id] INT NOT NULL,
    CONSTRAINT [ECO_EVENTO_PISOS_FK] PRIMARY KEY CLUSTERED ([Evento_id] ASC, [Piso_id] ASC),
    CONSTRAINT [ECO_EVENTO_PISO_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_EVENTO_PISOS_EVENTO_FK] FOREIGN KEY ([Evento_id]) REFERENCES [dbo].[ECOEMPRESARIAS_EVENTOS_TB] ([Evento_id]),
    CONSTRAINT [ECO_EVENTO_PISOS_PISO_FK] FOREIGN KEY ([Piso_id]) REFERENCES [dbo].[ECOEMPRESARIAS_PISOS_TB] ([Piso_id])
);

