CREATE TABLE [dbo].[ECOEMPRESARIAS_EMPRENDEDOR_TB] (
    [Emprendedor_id] INT           NOT NULL,
    [Cedula]         VARCHAR (12)  NOT NULL,
    [Telefono]       VARCHAR (15)  NOT NULL,
    [Email]          VARCHAR (200) NOT NULL,
    [Estado_id]      INT           NOT NULL,
    [Usuario_id]     INT           NOT NULL,
    CONSTRAINT [ECO_EMPRENDEDOR_PK] PRIMARY KEY CLUSTERED ([Emprendedor_id] ASC),
    CONSTRAINT [ECO_EMPRENDEDOR_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_EMPRENDEDOR_USUARIO_FK] FOREIGN KEY ([Usuario_id]) REFERENCES [dbo].[ECOEMPRESARIAS_USUARIOS_TB] ([Usuario_id]),
    CONSTRAINT [ECO_CEDULA_EMPRENDEDOR_UNQ] UNIQUE NONCLUSTERED ([Cedula] ASC),
    CONSTRAINT [ECO_EMAIL_EMPRENDEDOR_UNQ] UNIQUE NONCLUSTERED ([Email] ASC)
);

