CREATE TABLE [dbo].[ECOEMPRESARIAS_DETALLE_FACTURAS_TB] (
    [Factura_id]  INT             NOT NULL,
    [Producto_id] INT             NOT NULL,
    [Cantidad]    DECIMAL (10, 2) NOT NULL,
    [Precio]      DECIMAL (10, 2) NOT NULL,
    [Estado_id]   INT             NOT NULL,
    CONSTRAINT [ECO_DETALLE_FACTURAS_PK] PRIMARY KEY CLUSTERED ([Factura_id] ASC, [Producto_id] ASC),
    CONSTRAINT [ECO_DETALLE_FACT_CANT_CHK] CHECK ([Cantidad]>(0)),
    CONSTRAINT [ECO_DETALLE_FACT_PRECIO_CHK] CHECK ([Precio]>=(0)),
    CONSTRAINT [ECO_DETALLE_FACT_ESTADO_FK] FOREIGN KEY ([Estado_id]) REFERENCES [dbo].[ECOEMPRESARIAS_ESTADOS_TB] ([Estado_id]),
    CONSTRAINT [ECO_DETALLE_FACT_FACTURA_FK] FOREIGN KEY ([Factura_id]) REFERENCES [dbo].[ECOEMPRESARIAS_FACTURAS_TB] ([Factura_id]),
    CONSTRAINT [ECO_DETALLE_FACT_PRODUCTO_FK] FOREIGN KEY ([Producto_id]) REFERENCES [dbo].[ECOEMPRESARIAS_PRODUCTO_TB] ([Producto_id])
);

