CREATE TABLE [dbo].[ECOEMPRESARIAS_DETALLE_PEDIDOS_TB] (
    [DetallePedido_id] INT              IDENTITY (1, 1) NOT NULL,
    [Pedido_id]        INT              NOT NULL,
    [Producto_id]      UNIQUEIDENTIFIER NOT NULL,
    [Cantidad]         INT              NOT NULL,
    [PrecioUnitario]   DECIMAL (18, 2)  NOT NULL,
    [Subtotal]         DECIMAL (18, 2)  NOT NULL,
    CONSTRAINT [PK_ECOEMPRESARIAS_DETALLE_PEDIDOS] PRIMARY KEY CLUSTERED ([DetallePedido_id] ASC),
    CONSTRAINT [FK_ECOEMPRESARIAS_DETALLE_PEDIDOS_PEDIDO] FOREIGN KEY ([Pedido_id]) REFERENCES [dbo].[ECOEMPRESARIAS_PEDIDOS_TB] ([Pedido_id]),
    CONSTRAINT [FK_ECOEMPRESARIAS_DETALLE_PEDIDOS_PRODUCTO] FOREIGN KEY ([Producto_id]) REFERENCES [dbo].[ECOEMPRESARIAS_PRODUCTO_TB] ([Producto_id])
);

