CREATE TABLE [dbo].[ECOEMPRESARIAS_PRODUCTOS_POR_CARRITO_TB] (
    [Carrito_id]  UNIQUEIDENTIFIER NOT NULL,
    [Producto_id] UNIQUEIDENTIFIER NOT NULL,
    [Cantidad]    DECIMAL (10, 2)  NOT NULL,
    CONSTRAINT [ECO_PRODUCTOS_POR_CARRITO_TB_PK] PRIMARY KEY CLUSTERED ([Carrito_id] ASC, [Producto_id] ASC),
    CONSTRAINT [ECO_PRODUCTOS_POR_CARRITO_TB_CANTIDAD_CHK] CHECK ([Cantidad]>(0)),
    CONSTRAINT [ECO_PRODUCTOS_POR_CARRITO_TB_CARRITO_FK] FOREIGN KEY ([Carrito_id]) REFERENCES [dbo].[ECOEMPRESARIAS_CARRITO_TB] ([Carrito_id]),
    CONSTRAINT [ECO_PRODUCTOS_POR_CARRITO_TB_PRODUCTO_FK] FOREIGN KEY ([Producto_id]) REFERENCES [dbo].[ECOEMPRESARIAS_PRODUCTO_TB] ([Producto_id])
);

